### ISSUE TITLE
bu fw nin bir kucugu olsa tadindan yenmez

### ISSUE THREAD

**Issue by TheYkk** [izniburak/nur#1]
Eloquent ORM support. (Laravel Eloquent ORM)
Laravel Query Builder support. (Laravel Query Builder)
Blade Template Engine support. (Laravel Blade)
Laravel Eloquent Migration System support with PHPMig. (Laravel Migration - PHPMig)
Collections support. (Laravel Collections)
Useful array and string helpers. (Laravel Helpers)

sunlar kalksa yerine daha mini seyler gelse
helperler ve template engine kalsin onlarin da minisi olsun  

digerleri silinsin

birde core diye ayri sey olusturmak biraz sacma geldi

**Comment by izniburak** [comment]
Merhabalar,
Bunlar zaten ServiceProvider olarak configure edilebiliyor. Bunlara bağımlı değilsin. Örneğin template için blade kullanabilirsin ama ben normal klasik olarak HTML içinde PHP yazarak bi'şeyler yapacağım dersen, onu da yapabilirsin. Buradaki çoğu şey developmen yaparken en çok ihtiyaç duyulan şeyler. Ayrıca güncel yaklaşımlar olduğu için, kullanırken faydalı da oluyor. 

Core diye ayrı bir repo olması ise, Framework ana dosyaları üzerinde sürekli değişiklik ve geliştirme yapılıyor olması. Fırsat buldukça yeni şeyler eklemeye çalışıyorum. Böylece 'composer update' komutu ile en son güncellemeleri alma fırsatı olmuş oluyor. 

Şu an en büyük eksik, dokümantasyon. Onu da halletmeye çalışıyorum ama aksıyor ne yazık ki :)
