### ISSUE TITLE
Problem with XML PHP Extension

### ISSUE THREAD

**Issue by peter279k** [izniburak/nur#2]
As title, it seems that this `nur` framework requires some PHP XML extensions.

But related PHP XML extensions are as follows:

- libxml
- xml
- xmlreader
- xmlwriter

Which extensions need for this framework?

And which `xml` functions used for this framework?

@izniburak, do you have any idea about this?

**Comment by izniburak** [comment]
Hi @peter279k ,
Currently, libxml and xml are required. But Nur is still in the process of development. It can be change.

**Comment by peter279k** [comment]
@izniburak, thanks for your reply.

Perhaps some extensions need to be defined on `composer.json`.

**Comment by izniburak** [comment]
I'm thinking to add all required extensions to composer.json when I completed development process in my mind :) Thank you.
